# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bug It' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	 # Pods for Bug It
	 pod 'GoogleAPIClientForREST/Sheets'
 	 pod 'GoogleSignIn'

end
